language: node_js
node_js:
  - '10'
  - '8'
notifications:
  email: false
before_install:
  - "npm i -g npm@latest"
install:
  - npm install
  - npm install -g codecov
before_script:
  - npm prune
script:
  - npm run cover
  - codecov
